pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('backend/order-management') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('backend/order-management') {
                    sh 'docker build -t order-management:latest .'
                }
            }
        }
    }
}
